stages:
  - docker

.builder: &builder
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: docker
  variables:
    RELEASE: "master"
  before_script:
    - cd $CI_JOB_NAME
  script:
    - docker build --build-arg RELEASE=$RELEASE -t bennu/$CI_JOB_NAME:${RELEASE#"v"} .
    - if [ $RELEASE != "master" ]; then
      docker tag bennu/$CI_JOB_NAME:${RELEASE#"v"} bennu/$CI_JOB_NAME:latest;
      fi
  after_script:
    - echo $HUB_PASS | docker login -u $HUB_USER --password-stdin
    - docker push bennu/$CI_JOB_NAME
    - docker logout

govc:
  <<: *builder
  variables:
    RELEASE: "v0.18.0"

kustomize:
  <<: *builder
  variables:
    RELEASE: "v1.0.8"

hugo:
  <<: *builder
  variables:
    RELEASE: "v0.49"
