stages:
  - docker

.builder: &builder
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: docker
  variables:
    RELEASE: "master"
  script:
    - cd $CI_JOB_NAME
    - docker build --build-arg RELEASE=$RELEASE -t bennu/$CI_JOB_NAME:$RELEASE .
    - echo $HUB_PASS | docker login -u $HUB_USER --password-stdin
    - docker push bennu/$CI_JOB_NAME:$RELEASE
    - docker rmi -f bennu/$CI_JOB_NAME:$RELEASE
    - docker logout

govc:
  <<: *builder
